---
- name: GET DEVICE INFO
  hosts: testhosts
  connection: network_cli
  gather_facts: no

  tasks:
    - name: GATHER ROUTER INT INFO
      ios_facts:
        gather_subset:
          - config

    - debug:
        msg: "Node {{ inventory_hostname }} is running {{ ansible_net_version }}"