---
#https://gdykeman.github.io/2018/06/26/ios-upgrades/

- name: Prep for update ios firmware
  hosts: testhosts
  connection: network_cli
  gather_facts: no

  vars:
    compliant_ios_ver: 16.08.01a
    ny_ios_filename: txt.txt

  tasks:
    - name: gather facts from node
      ios_facts:

    - name: Prep IOS image upgrade
      block:
      - name: copy file to host
        command: "scp {{ ny_ios_filename }} {{ ansible_user }}@{{inventory_hostname}}:{{ ny_ios_filename }}"

      #- name: Set boot image
        #ios_command:
          #command: "boot system flash:{{ ny_ios_filename }}"

      when: ansible_net_version != compliant_ios_ver

    - name: GATHER ROUTER FACTS FOR VERIFICATION
      ios_facts:
